name: thetentative
favicon: null
layout_spectrum: 0.7354200927074999
typography_spectrum: 0.7361232037656009
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.34678698261268437
  lightness: 0.7631067186594009
  saturation: 0.6448977484833449
  rhythmicContrast: 0.7111543091014028
purpose: []
